# Generated by Django 4.0.1 on 2022-01-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columns_name', models.CharField(max_length=140)),
                ('columns_name_kr', models.CharField(max_length=140)),
                ('columns_type', models.CharField(max_length=140)),
                ('columns_desc', models.TextField(blank=True)),
                ('standard_y', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_id', models.ForeignKey(db_column='feature_id', on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='features.feature')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
