# Generated by Django 4.0.1 on 2022-01-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '__first__'),
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='feature_id',
            field=models.ForeignKey(db_column='feature_id', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='features.feature'),
        ),
    ]
