# Generated by Django 4.0.1 on 2022-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='url_link',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
